# Generated by Django 4.0.5 on 2022-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('verification_code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
